import React from "react";
import NextHead from 'next/head'

export const Head: React.FC = () => {
    return (
        <NextHead>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />

        </NextHead>
    )
}